version: '3'
services:
  app:
    build: .
    container_name: flask_boiler
    working_dir: /app
    env_file: secrets.env
    environment:
      FLASK_APP: ./flask_boiler/main.py
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    depends_on:
      - 'db'

  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
